### ISSUE TITLE
Target URL matching regex should allow URI valid characters 

### ISSUE THREAD

**Issue by mabdelfattahm** [EXXETA/openapi-cop#248]
#### Description
I am trying to use this to validate a hosted backend whose target URL happens to include dots and dashes, the target URL validation regex used only validates word characters `/w` and it should allow any URI valid character.

#### To Reproduce
Try any URL with dots, dashes in it, i.e. `http://demo-server:8000/v1/`

#### Tasks
Modify target URL validation regex to allow more characters, something like `\w+:\/\/[A-Za-z0-9\-._~:\/?#[\]@!$&'()*+,;=]+:(\d{4})(\/|$)`

**Comment by siimsoni** [comment]
On a related note, the port number is also too constrictive, as it does not accept port 80 nor any of the ports in the higher range. 

For validation purposes, it would make sense to check if there is _any_ number, although I would prefer it to default to port 80 for http and 443 for https protocols.
