### ISSUE TITLE
Cannot cURL requests into the containerized application

### ISSUE THREAD

**Issue by mabdelfattahm** [EXXETA/openapi-cop#249]
#### Description
I am trying to use the docker image provided but I am not able to pass in requests to the containerized application. I think this is because the application is listening on `localhost` or `127.0.0.1`. I am exposing the default port `8888` using `docker run -p 8888:8888` and the response is `curl: (52) Empty reply from server`

#### To Reproduce
Run the docker image using `docker run -p 8888:8888 lxlu/openapi-cop`. Try any cURL request to http://127.0.0.1:8888

#### Tasks
Change default host address to `0.0.0.0` or add the ability to modify application host name using the environment variables

**Comment by LexLuengas** [comment]
Closed in 51cff33.
